server:
  port: 9083
  servlet:
    context-path: /cgp-saas-platform
spring:
  application:
    name: cgp-saas-platform
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.203:8848 # 将gateway注册到nacos
  # 数据库连接配置
  datasource:
    name: test
    url: jdbc:mysql://192.168.1.201:3306/cgp_saas_dev?useUnicode=true&autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: yidianwan
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  # redis连接配置
  redis:
    # Redis数据库索引（默认为0）
    database: 13
    # Redis服务器地址
    host: 192.168.1.203
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

feign:
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 180000

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ydw.platform.model.db
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type:  1
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

#日志
logging:
  level:
    com.ydw.platform: debug

#shiro和jwt配置
shiro:
  # JWT认证加密私钥(Base64加密)
  encryptJWTKey: Q0dQLVNBQVMtR0FNRQ==
  # AccessToken过期时间-5分钟-5*60(秒为单位)
  accessTokenExpireTime: 1800

#外部服务url
url:
  paasApi: http://192.168.1.203:9000
  pics: http://picsdev.yidianwan.cn/pics/

#qq登录回调
qq:
  url:
    http: http://clientdev.yidianwan.cn/
#断线配置
offline:
  #超时连接秒数
  timeout: 30
  #offline scan period(掉线扫描频率，分钟)
  scanPeriod: 1
  #默认5秒后释放
  releaseTime: 5
