server:
  port: 8085
  servlet:
    context-path: /cgp-paas-resource
spring:
  application:
    name: cgp-paas-resource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 将gateway注册到nacos
  # 数据库连接配置
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/cgp_paas?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: Yidianwan!23
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  # redis连接配置
  redis:
    # Redis数据库索引（默认为0）
    database: 5
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

feign:
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000
  httpclient:
    enabled: false
  okhttp:
    enabled: true

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    # 数据库相关配置
    db-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

url:
  pics: http://filesdev.yidianwan.cn/pics/

#重启异步处理(秒)
rebooting:
  #重启状态扫描周期
  period: 60
  #重启超时时间
  timeout: 600

#准备中异步处理（秒）
preparing:
  #扫描周期
  period: 60
  #超时时间
  timeout: 150