server:
  port: 9083
  servlet:
    context-path: /cgp-saas-admin
spring:
  application:
    name: cgp-saas-admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 5120MB
      max-request-size: 5120MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 将gateway注册到nacos

  # 数据库连接配置
  datasource:
    name: test
    url: jdbc:mysql://192.168.0.75:3306/cgp_saas?useUnicode=true&autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: Yidianwan!23
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  # redis连接配置
  redis:
    # Redis数据库索引（默认为0）
    database: 13
    # Redis服务器地址
    host: 192.168.0.75
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

feign:
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 180000

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ydw.admin.model.db
  global-config:
    # 数据库相关配置
    db-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

#日志
logging:
  level:
    com.ydw.admin: debug


#外部服务url
url:
  paasApi: http://127.0.0.1:9000
  pics: http://filesdev.yidianwan.cn/pics/
#  customizeDomain: https://files.yidianwan.cn/pics/
# 自定义上传文件配置
config:
  uploadPath: pics/game/
  back: pics/paas/game/
  netbarPic: netbarPic/
  netbarUpload: pics/netbarPic/
  faqPic: pics/faq/
  appPicture: /home/web/files/pics/app_pictures/
#ftp配置
ftp:
  address: 121.36.97.240
  port: 21
  userName: ydw
  passWord: Yidianwan!23
  upgradeFile: upgrade/app_update_conifg.txt


#Paas   ftp配置
passFtp:
  address: 121.36.97.240
  port: 21
  userName: ydw
  passWord: Yidianwan!23
  upgradeFile: upgrade/app_update_conifg.txt

#短信配置
sms:
  appId: 1400349137
  appKey: 125873d60b2cee73ca4161ba2fb74edb
  sign: 易点玩云游戏
  defaultPhone1: 19907110310
  defaultPhone2: 17798207200
  defaultPhone3: 17720537558
  templateIds:
    #提现审批通过的templateId
    apply_withdraw_success: 836377
    #提现审批失败的templateId
    apply_withdraw_fail: 836378
    #巡检id
    illegalUserInspectionId: 962437