server:
  port: 8083
  servlet:
    context-path: /cgp-paas-meterage
spring:
  application:
    name: cgp-paas-meterage
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 将gateway注册到nacos
  # 数据库连接配置
  datasource:
    name: test
    url: jdbc:mysql://192.168.0.75:3306/cgp_paas?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: Yidianwan!23
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 50
  # redis连接配置
  redis:
    # Redis数据库索引（默认为0）
    database: 3
    # Redis服务器地址  
    host: 192.168.0.75
    # Redis服务器连接端口  
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    #集群配置
    #cluster:
      # 各 Redis 节点信息
      #nodes: 192.168.131.231:6379,192.168.131.231:6379,192.168.131.231:6379
      # 执行命令超时时间
      #command-timeout: 15000
      # 重试次数
      #max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      #max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      #max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      #max-wait: -1
      # 连接池中的最大空闲连接
      #max-idle: 8
      # 连接池中的最小空闲连接
      #min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      #test-on-borrow: true

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ydw.meterage.model.db
  global-config:
    # 数据库相关配置
    db-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
    #驼峰下划线转换
      db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
      refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

logging:
  level:
    com.ydw.meterage: debug